<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vagamatch</groupId>
    <artifactId>vagamatch</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>vagamatch</name>
    <description>Microsserviços que analisam vagas com IA e calculam o match com o perfil do candidato</description>

    <modules>
        <module>vaga-service</module>
        <module>analise-service</module>
    </modules>
</project>
