server:
  port: 8081

spring:
  application:
    name: analise-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:vagamatch}
    password: ${RABBIT_PASSWORD:vagamatch}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
